### ISSUE TITLE
Shut off keyboard hotkey functionalities when renaming a layer

### ISSUE THREAD

**Issue by PotassiumK** [DDMAL/Pixel.js#221] opened 2017-08-14 15:28 UTC
The more hotkeys there are, the more likely their functionalities will be triggered when changing a layer name. This is undesirable, especially as hotkeys can accomplish stronger functionalities or trigger an exception, such as selecting a layer that does no exist when adding a number to the name of a layer.

**Comment by zeyadhazem** [comment] 2017-08-15 18:25
duplicate of #113

**Closed as completed by zeyadhazem** 2017-08-15 18:25 UTC
Labels: enhancement, Priority: High, Component: Surface
