### ISSUE TITLE
Render Diva6 images in the browser

### ISSUE THREAD

**Issue by PotassiumK** [DDMAL/Pixel.js#32] opened 2017-05-10 13:21 UTC

**Comment by PotassiumK** [comment] 2017-05-10 19:20
@ahankinson on line 212 of renderer.js
`this._compositeImages[pageIndex].getTiles(this._zoomLevel).forEach((source) =>`

As I understand it, this line gets the tiles at the current zoom level from the composite images. What does `(source)` refer to?

**Comment by PotassiumK** [comment] 2017-05-10 19:43
Also, is it normal that we can't see the assets folder containing diva.js within intelliJ?

**Comment by zeyadhazem** [comment] 2017-05-12 20:20
Duplicate of DDMAL/diva.js#378

**Closed as completed** 2017-05-12 20:20 UTC
Labels: Bug
