### ISSUE TITLE
Adapt wand plugin to Pixel.js

### ISSUE THREAD

**Issue by PotassiumK** [DDMAL/Pixel.js#168] opened 2017-07-06 20:48 UTC
There is a functional algorithm of the magic wand tool for OpenLayers. The idea is to adapt the algorithm to Pixel.js without using open layers in any way.

**Comment by PotassiumK** [comment] 2017-07-19 13:51
Currently, the `wand.js` code is a non-ol implementation that needs to be updated to work with the rest of the code.

**Comment by zeyadhazem** [comment] 2017-08-03 15:21
duplicate of #78

**Closed as completed by zeyadhazem** 2017-08-03 15:22 UTC
Labels: Priority: High, Feature Request, Component: Core
